### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by ranebull** [abdesslem/CTF#11]
I have some problem:
root@b0cfab576e2f:/CTF# python run.py check
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/CTF/ctf.py:14: ExtDeprecationWarning: Importing flask.ext.mail is deprecated, use flask_mail instead.
  from flask.ext.mail import Message
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from ctf import app
  File "/CTF/ctf.py", line 19, in <module>
    import models
  File "/CTF/models.py", line 6, in <module>
    class User(UserMixin, ctf.db.Model):  
AttributeError: 'module' object has no attribute 'db'

**Comment by qianfei11** [comment]
same problem...
